server:
  port: 8090
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    #buffers-per-region: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
    threads:
      # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
      # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
      worker: 64
      io: 8
  servlet:
    context-path: /fusion
spring:
  application:
    name: fusion
  web:
    resources:
      add-mappings: false
  datasource:
    url: YK3pbx9cTsIhhPnvLJL/GYRd7xlHazaBl65hy9a95bEWFe3Zb6K4z4RUpPgNBvpv
    username: Maccmmrq5WBTUh1l/jIY+g==
    password: QA2Cr8IO+jgJWrcIZZZZmw==
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 100
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      password: QA2Cr8IO+jgJWrcIZZZZmw==
      database: 1
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
# 是否开启sql记录
mybatis:
  sqlLog: true
mybatis-flex:
  mapper-locations: classpath*:mapper/**/*.xml
logging:
  level:
    root: info
    cn.net.fusion: debug
    org.springframework.web: error
  file:
    path: ${user.home}/fusionLog
# sa-token 配置
sa-token:
  token-style: random-128
  # 15分钟内无操作，token则会立即过期(单位:秒)
  active-timeout: 900
  token-name: Authorization
  # token 前缀
  token-prefix: Bearer
  # 是否允许同一账号多地同时登录
  is-concurrent: false
  # 是否多端共享 token
  is-share: false
  is-log: false
  # 是否读取 cookie 中的 token，从header中读取
  is-read-cookie: false
